services:
  - type: web
    name: advbox-oauth-proxy
    runtime: docker
    plan: free
    envVars:
      - key: ADVBOX_URL
        value: https://mcp.limaamorim.com.br
      - key: ADVBOX_TOKEN
        value: f869c4969f2e02f9245ee6a2d12db5788d92784da6badc9bba4d1d29a2bcc03c
      - key: PORT
        value: 4000
      - key: PUBLIC_URL
        generateValue: false
        value: https://advbox-oauth-proxy.onrender.com
      - key: ADVBOX_REST_URL
        value: https://app.advbox.com.br/api/v1
      - key: ADVBOX_REST_TOKEN
        value: 4aganI4V9kABSyo6jHGlDbhyN9mcYwTbIQU8tu2oDsNyuoi6RLKplLZ3kIE3
      - key: CHATGURU_URL
        value: https://s17.chatguru.app/api/v1
      - key: CHATGURU_KEY
        value: BIN67XARJAKDZYJUCCG0852E7HH6GJREVBOQMHRQZMRIMQD00YJS1SVON5XXQD04
      - key: CHATGURU_ACCOUNT
        value: 644a7348af2b76abbc1553dd
      - key: CHATGURU_PHONE
        value: 644a765d64007ea81fe9076f
